### ISSUE TITLE
Requirements of Chronicle and assemblies to Bee

### ISSUE THREAD

**Issue by bingyanglin** [iotaledger/bee-rfcs#9]
1. Configuration format file should be aligned with one format. [HOCON](https://en.wikipedia.org/wiki/HOCON), e.g., if adopted in Bee, then it should be also adopted in [Chronicle](https://docs.iota.org/docs/node-software/0.1/chronicle/introduction/overview), to make the configuration files consistent and easy to maintain. In addition, adaptive runtime configuration should be implemented, in this way, e.g., a crashed node/chronicle can read an updated configuration file and reboot itself (or be rebooted) properly.

2. Because we never know what kinds of data the users need for their applications/analysis, one of the flexible approaches for data collection is to use Bee [gossip](https://iota.stackexchange.com/questions/2202/how-is-the-gossip-protocol-which-is-used-by-iota-classified) and Bee [solidifier](https://docs.iota.org/docs/node-software/0.1/iri/concepts/the-ledger) to subscribe and prune transactions. A dedicated pruner should be designed in the [Chronicle](https://docs.iota.org/docs/node-software/0.1/chronicle/introduction/overview), so users can choose which kinds of data to remove.

3. If the user wants to collect confirmed transactions only, then Bee [EEE](https://github.com/iotaledger/ixi/blob/master/docs/inter-ixi.md) should be adopted, so confirmed transactions can be subscribed directly by the [Chronicle](https://docs.iota.org/docs/node-software/0.1/chronicle/introduction/overview), without post processing.

4. In the [Chronicle](https://docs.iota.org/docs/node-software/0.1/chronicle/introduction/overview)’s point of view, it is necessary to make sure that the subscribed Bee node(s) can see the whole tangle (except for the old transactions removed after [snapshots](https://iota-news.com/iota-snapshot/)), and every transaction visible to the node can be sent to the [Chronicle](https://docs.iota.org/docs/node-software/0.1/chronicle/introduction/overview) by Bee data dissemination protocols ([EEE](https://github.com/iotaledger/ixi/blob/master/docs/inter-ixi.md) or [gossip](https://iota.stackexchange.com/questions/2202/how-is-the-gossip-protocol-which-is-used-by-iota-classified)), so the [Chronicle](https://docs.iota.org/docs/node-software/0.1/chronicle/introduction/overview) will not lose any (confirmed) transaction. Otherwise, which kinds of transactions cannot be sent to the [Chronicle](https://docs.iota.org/docs/node-software/0.1/chronicle/introduction/overview) should be known beforehand, and the user can know these specific transactions cannot be collected.

**Comment by louaykamel** [comment]
1- Adaptive runtime configuration is a hard requirement for Chronicle, a Chronicle node should be able to adapt dynamically with the topology changes of Scylla cluster (ie adding/removing scylla node), it should be added/removed to/from the _NODES_: param in HOCON config file. 

2- Chronicle somehow should eventually have the full picture of tangle, that's why I think solidifier is a hard-requirement. 

Would you please expand the context about "A dedicated pruner should be designed in the chronicle"? btw TTL(time-to-live) feature in scylladb will enable us to pruner a given row(s) on interval.

3- Agree

4- This is a very important point, @thibault-martinez do you think solidifier will handle this case?

**Comment by bingyanglin** [comment]
1. Agree. The adaptive runtime configuration (which can be used to improve performance) should be classified into a research topic. Allowing to dynamically configure the topology changes only is good enough for normal usage.

2. The pruner I mean can be regarded as a filter, used to remove specific data before storing them to the database. The user can define which kinds of data they don't want to collect, so as to reduce the storage cost. The TTL feature you mentioned is a promising approach to achieve the same goal. The difference is that in TTL feature we need to remove data from the database, while using a pruner before data storing can save the removing effort.
